Repository govuk-one-login/mobile-ios-common, pull requests merged in 2023-10, with the labels that each got.

#8 feat: Adding demo project
  .github/workflows/pull-request.yml
  .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
  GDSCommon-Demo.xcworkspace/contents.xcworkspacedata
  GDSCommon-Demo.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GDSCommon-Demo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.pbxproj
  GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  GDSCommon-Demo/GDSCommon-Demo.xcodeproj/xcshareddata/xcschemes/GDSCommon-Demo.xcscheme
  GDSCommon-Demo/GDSCommon-Demo/AppDelegate.swift
  GDSCommon-Demo/GDSCommon-Demo/Assets.xcassets/AccentColor.colorset/Contents.json
  GDSCommon-Demo/GDSCommon-Demo/Assets.xcassets/AppIcon.appiconset/Contents.json
  GDSCommon-Demo/GDSCommon-Demo/Assets.xcassets/Contents.json
  GDSCommon-Demo/GDSCommon-Demo/Assets.xcassets/licence.imageset/Contents.json
  GDSCommon-Demo/GDSCommon-Demo/Assets.xcassets/licence.imageset/Group 70.svg
  GDSCommon-Demo/GDSCommon-Demo/Base.lproj/Demo.storyboard
  GDSCommon-Demo/GDSCommon-Demo/Base.lproj/LaunchScreen.storyboard
  GDSCommon-Demo/GDSCommon-Demo/DemoViewController.swift
  GDSCommon-Demo/GDSCommon-Demo/Info.plist
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockButtonViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockGDSInstructionsViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockInstructionWithImageViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockModalInfoViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
  GDSCommon-Demo/GDSCommon-Demo/SceneDelegate.swift
  GDSCommon-Demo/GDSCommon-DemoTests/GDSCommon_DemoTests.swift
  GDSCommon-Demo/GDSCommon-DemoTests/GDSInstructionsViewControllerTests.swift
  GDSCommon-Demo/GDSCommon-DemoTests/InstructionsWithImageViewControllerTests.swift
  GDSCommon-Demo/GDSCommon-DemoTests/MockGDSInstructionsViewModel.swift
  GDSCommon-Demo/GDSCommon-DemoTests/ModalInfoViewControllerTests.swift
  GDSCommon-Demo/GDSCommon-DemoTests/TestExtensions/UIView+Test_Extensions.swift
  GDSCommon-Demo/GDSCommon-DemoTests/TestExtensions/XCTestCase.swift
  GDSCommon-Demo/UnitTestPlan.xctestplan
  Package.resolved
  README.md
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage.xib
  Tests/GDSCommonTests/ButtonStylesTests.swift
  Tests/GDSCommonTests/ComponentTests/Text+ExtensionsTests.swift
  Tests/GDSCommonTests/GDSLocalisedStringTests.swift
  Tests/GDSCommonTests/TestExtensions/Color+ExtensionsTests.swift
Labels: documentation

#11 feat: add Intro Screen
  GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.pbxproj
  GDSCommon-Demo/GDSCommon-Demo/Assets.xcassets/badge.imageset/Contents.json
  GDSCommon-Demo/GDSCommon-Demo/Assets.xcassets/badge.imageset/rounded logo gov-uk copy.svg
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockIntroViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
  GDSCommon-Demo/GDSCommon-DemoTests/IntroViewControllerTests.swift
  Sources/GDSCommon/README.md
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IntroView/IntroView.xib
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IntroView/IntroViewController.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IntroView/IntroViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/ModalInfoView/ModalInfoViewController.swift
Labels: enhancement

#9 feat: add DatePicker screen and view model
  GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.pbxproj
  GDSCommon-Demo/GDSCommon-Demo/DemoViewController.swift
  GDSCommon-Demo/GDSCommon-Demo/Extensions/ViewControllerInitialiser+Extensions.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockDatePickerScreenViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockDatePickerViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
  GDSCommon-Demo/GDSCommon-DemoTests/DatePickerScreenViewControllerTests.swift
  GDSCommon-Demo/GDSCommon-DemoTests/MockDatePickerScreenViewModel.swift
  GDSCommon-Demo/GDSCommon-DemoTests/Mocks/MockListOptionsViewModel.swift
  GDSCommon-Demo/GDSCommon-DemoTests/TestExtensions/Date+Extensions.swift
  Sources/GDSCommon/README.md
  Sources/GDSCommon/UI/UIKit/SharedViews/Components/DatePickerViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Components/ReusableDatePickerViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/DatePicker/DatePicker.xib
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/DatePicker/DatePickerScreenViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/DatePicker/DatePickerViewController.swift
  Tests/GDSCommonTests/ComponentTests/DatePickerViewModelTests.swift
  Tests/GDSCommonTests/TestExtensions/Date+Extensions.swift
Labels: enhancement

#10 feat: Add TextInput screen pattern
  GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.pbxproj
  GDSCommon-Demo/GDSCommon-Demo/Extensions/ViewControllerInitialiser+Extensions.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockTextFieldViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockTextInputViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
  GDSCommon-Demo/GDSCommon-DemoTests/Mocks/MockTextInputViewModel.swift
  GDSCommon-Demo/GDSCommon-DemoTests/TextInputViewControllerTests.swift
  Sources/GDSCommon/Extensions/UIKit/UIView+BorderExtension.swift
  Sources/GDSCommon/README.md
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/TextInput/TextFieldViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/TextInput/TextInput.xib
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/TextInput/TextInputViewController.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/TextInput/TextInputViewModel.swift
  Tests/GDSCommonTests/ComponentTests/DialogViewTests.swift
  Tests/GDSCommonTests/ComponentTests/Mocks/MockTextFieldViewModel.swift
  Tests/GDSCommonTests/ComponentTests/Mocks/MockTextInputViewModel.swift
Labels: enhancement

#20 fix: adjust default border width
  Sources/GDSCommon/Extensions/UIKit/UIView+BorderExtension.swift
Labels: bug

#21 feat: added optional right bar button item to Instructions Screen Pattern
  GDSCommon-Demo/GDSCommon-Demo/Extensions/ViewControllerInitialiser+Extensions.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockGDSInstructionsViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
  GDSCommon-Demo/GDSCommon-DemoTests/GDSInstructionsViewControllerTests.swift
  GDSCommon-Demo/GDSCommon-DemoTests/MockGDSInstructionsViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSInstructions/GDSInstructionsViewController.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSInstructions/GDSInstructionsViewModel.swift
Labels: enhancement

#22 feat: Icon Options screen
  GDSCommon-Demo/GDSCommon-Demo.xcodeproj/project.pbxproj
  GDSCommon-Demo/GDSCommon-Demo/Extensions/ViewControllerInitialiser+Extensions.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockIconScreenViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockOptionViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
  GDSCommon-Demo/GDSCommon-DemoTests/IconScreenViewControllerTests.swift
  GDSCommon-Demo/GDSCommon-DemoTests/IntroViewControllerTests.swift
  Sources/GDSCommon/README.md
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IconScreenView/IconScreenView.xib
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IconScreenView/IconScreenViewController.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IconScreenView/IconScreenViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IconScreenView/OptionView.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IconScreenView/OptionView.xib
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/IconScreenView/OptionViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage/InstructionsWithImageViewController.swift
Labels: enhancement
