Repository govuk-one-login/mobile-ios-common, pull requests merged in 2023-11, with the labels that each got.

#23 feat!: adding-optional-parameters-for-image-instructions
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockButtonViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockInstructionWithImageViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockOptionViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
  GDSCommon-Demo/GDSCommon-DemoTests/GDSInstructionsViewControllerTests.swift
  GDSCommon-Demo/GDSCommon-DemoTests/InstructionsWithImageViewControllerTests.swift
  Sources/GDSCommon/UI/SwiftUI/SharedViews/Buttons/ButtonView.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Buttons/ButtonIconViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Buttons/ButtonViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Components/BulletView.xib
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/GDSInstructions/GDSInstructionsViewController.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage/InstructionsWithImage.xib
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage/InstructionsWithImageViewController.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage/InstructionsWithImageViewModel.swift
  Tests/GDSCommonTests/ComponentTests/Mocks/MockButtonViewModel.swift
Labels: enhancement

#24 fix: adding missing icon check in Primary Button
  GDSCommon-Demo/GDSCommon-DemoTests/InstructionsWithImageViewControllerTests.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/InstructionsWithImage/InstructionsWithImageViewController.swift
Labels: bug

#26 feat: added right bar button to qr scanner
  GDSCommon-Demo/GDSCommon-Demo/Mocks/MockQRScanningViewModel.swift
  GDSCommon-Demo/GDSCommon-Demo/Mocks/Screens.swift
  GDSCommon-Demo/GDSCommon-DemoTests/ScanningViewControllerTests.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/Scanner/QRScanningViewModel.swift
  Sources/GDSCommon/UI/UIKit/SharedViews/Patterns/Scanner/ScanningViewController.swift
Labels: ready for review
